<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Dock.Avalonia" />
    <PackageReference Include="Dock.Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlaceRouter.Infrastructure\PlaceRouter.Infrastructure.csproj" />
    <ProjectReference Include="..\PlaceRouter.Presentation.Avalonia\PlaceRouter.Presentation.Avalonia.csproj" />
  </ItemGroup>

</Project>
