<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PlaceRouter.Application\PlaceRouter.Application.csproj" />
    <ProjectReference Include="..\PlaceRouter.Infrastructure\PlaceRouter.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
