<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PlaceRouter.Core\PlaceRouter.Core.csproj" />
    <ProjectReference Include="..\PlaceRouter.Domain\PlaceRouter.Domain.csproj" />
    <ProjectReference Include="..\PlaceRouter.Application\PlaceRouter.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\schemas\prdx\0.1\prdx-manifest.schema.json" Link="Schemas\prdx-manifest.schema.json" />
    <EmbeddedResource Include="..\..\schemas\prdx\0.1\prdx-project.schema.json" Link="Schemas\prdx-project.schema.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NJsonSchema" Version="11.6.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
